#define REDIS_GIT_SHA1 "c5ee3442"
#define REDIS_GIT_DIRTY "86"
#define REDIS_BUILD_ID "ukhost-1572605508"
#include "version.h"
#define REDIS_BUILD_ID_RAW REDIS_VERSION REDIS_BUILD_ID REDIS_GIT_DIRTY REDIS_GIT_SHA1
